-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 03:26:48 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zixin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zixin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zixin` DEFAULT CHARACTER SET utf8 ;
USE `zixin` ;

-- -----------------------------------------------------
-- Table `zixin`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`user` ;

CREATE TABLE IF NOT EXISTS `zixin`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `create_time` BIGINT(20) NULL,
  `home` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`company` ;

CREATE TABLE IF NOT EXISTS `zixin`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `uscc` VARCHAR(45) NULL,
  `create_time` BIGINT(20) NULL,
  `update_time` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uscc_UNIQUE` (`uscc` ASC),
  CONSTRAINT `fk_company__user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `zixin`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`article_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`article_type` ;

CREATE TABLE IF NOT EXISTS `zixin`.`article_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_article_type__parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `zixin`.`article_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`article` ;

CREATE TABLE IF NOT EXISTS `zixin`.`article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_id` INT NULL,
  `user_id` INT NULL,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `create_time` BIGINT(20) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_article__type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `zixin`.`article_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article__user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `zixin`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`req_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`req_type` ;

CREATE TABLE IF NOT EXISTS `zixin`.`req_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`user_req`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`user_req` ;

CREATE TABLE IF NOT EXISTS `zixin`.`user_req` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL,
  `type_id` INT NULL,
  `create_time` BIGINT(20) NULL,
  `content` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_req__user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `zixin`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_req_type__type_id`
    FOREIGN KEY (`type_id`)
    REFERENCES `zixin`.`req_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`file` ;

CREATE TABLE IF NOT EXISTS `zixin`.`file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`task` ;

CREATE TABLE IF NOT EXISTS `zixin`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_req_id` INT NULL,
  `create_time` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_task__user_req_id`
    FOREIGN KEY (`user_req_id`)
    REFERENCES `zixin`.`user_req` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`task_file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`task_file` ;

CREATE TABLE IF NOT EXISTS `zixin`.`task_file` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` INT NULL,
  `file_id` INT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_task_file__task_id`
    FOREIGN KEY (`task_id`)
    REFERENCES `zixin`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_file__file_id`
    FOREIGN KEY (`file_id`)
    REFERENCES `zixin`.`file` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`company_source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`company_source` ;

CREATE TABLE IF NOT EXISTS `zixin`.`company_source` (
  `id` INT NOT NULL,
  `company_id` INT NULL,
  `content` LONGTEXT NULL,
  `create_time` BIGINT(20) NULL,
  `update_time` BIGINT(20) NULL,
  `origin` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_company_source__company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `zixin`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zixin`.`user_req_company_source`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`user_req_company_source` ;

CREATE TABLE IF NOT EXISTS `zixin`.`user_req_company_source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_req_id` INT NULL,
  `company_source_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_req_company__user_req_id`
    FOREIGN KEY (`user_req_id`)
    REFERENCES `zixin`.`user_req` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_req_company__company_source_id`
    FOREIGN KEY (`company_source_id`)
    REFERENCES `zixin`.`company_source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`menu` ;

CREATE TABLE IF NOT EXISTS `zixin`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


-- -----------------------------------------------------
-- Table `zixin`.`menu_item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zixin`.`menu_item` ;

CREATE TABLE IF NOT EXISTS `zixin`.`menu_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NULL,
  `menu_id` INT NULL,
  `name` VARCHAR(45) NULL,
  `href` VARCHAR(45) NULL,
  `icon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_menu_item__parent_id`
    FOREIGN KEY (`parent_id`)
    REFERENCES `zixin`.`menu_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_menu_item__menu_id`
    FOREIGN KEY (`menu_id`)
    REFERENCES `zixin`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10000;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `zixin`.`menu`
-- -----------------------------------------------------
START TRANSACTION;
USE `zixin`;
INSERT INTO `zixin`.`menu` (`id`, `name`, `code`) VALUES (1, '后台菜单', 'admin');
INSERT INTO `zixin`.`menu` (`id`, `name`, `code`) VALUES (2, '前台菜单', 'home');

COMMIT;


-- -----------------------------------------------------
-- Data for table `zixin`.`menu_item`
-- -----------------------------------------------------
START TRANSACTION;
USE `zixin`;
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (1, NULL, 1, '公司管理', '/admin/company', 'fa fa-diamond');
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (2, NULL, 1, '文章管理', '/admin/article', 'fa fa-file');
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (3, NULL, 1, '用户管理', '/admin/user', 'fa fa-user');
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (4, NULL, 1, '申请管理', '/admin/req', 'fa fa-question');
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (5, NULL, 1, '任务管理', '/admin/task', 'fa fa-tasks');
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (6, NULL, 1, '菜单管理', '/admin/menu', 'fa fa-bars');
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (101, NULL, 2, '首页', '/', NULL);
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (102, NULL, 2, '介绍', 'http://www.baidu.com/s?wd=介绍', NULL);
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (103, NULL, 2, '新闻', 'http://www.baidu.com/s?wd=新闻', NULL);
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (104, NULL, 2, '图片', 'http://www.baidu.com/s?wd=图片', NULL);
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (105, NULL, 2, '视频', 'http://www.baidu.com/s?wd=视频', NULL);
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (106, NULL, 2, '博客', 'http://www.baidu.com/s?wd=博客', NULL);
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (107, NULL, 2, '股市', 'http://www.baidu.com/s?wd=股市', NULL);
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (108, NULL, 2, '普通资信', '/user/req', NULL);
INSERT INTO `zixin`.`menu_item` (`id`, `parent_id`, `menu_id`, `name`, `href`, `icon`) VALUES (7, 2, 1, '文章类型', '/admin/article_type', NULL);

COMMIT;

